WIP New Plugin: Home Connect
nymea/nymea-plugins pull request #259
Opened 2020-04-16 17:58 UTC by Boernsman

nymea-plugins pull request checklist:

- [ ] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [ ] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [ ] Did you update the plugin's README.md accordingly?

- [ ] Did you update translations (`cd builddir && make lupdate`)?

- [ ] If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker?

2020-10-19 10:36 UTC, mzanetti commented
Fails to load:

 W | ThingManager: Could not load plugin data of "/usr/lib/arm-linux-gnueabihf/nymea/plugins/libnymea_integrationpluginhomeconnect.so" 
 "Cannot load library /usr/lib/arm-linux-gnueabihf/nymea/plugins/libnymea_integrationpluginhomeconnect.so: (/usr/lib/arm-linux-gnueabihf/nymea/plugins/libnymea_integrationpluginhomeconnect.so: undefined symbol: _ZN28IntegrationPluginHomeConnect23onReceivedActiveProgramERK7QStringS2_RK5QHashIS0_8QVariantE)"
 W | ThingManager: Error loading plugin: "/usr/lib/arm-linux-gnueabihf/nymea/plugins/libnymea_integrationpluginhomeconnect.so"

2020-10-22 17:56 UTC, mzanetti requested changes
Pretty nice plugin. Needs some fixes tho. And a couple of questions.

2020-10-22 17:56 UTC, mzanetti commented on homeconnect/homeconnect.cpp
> +    m_codeChallenge = QUuid::createUuid().toString().remove('{').remove('}').remove("-");
.remove(QRegExp("[{}-]")

2020-10-22 17:56 UTC, mzanetti commented on homeconnect/homeconnect.cpp
> +    //TODO emit (dis)connected, (un)authenticated,
hmm... seems a somewhat important todo... Much to be done there or could we have it fixed still?

2020-10-22 17:56 UTC, mzanetti commented on homeconnect/integrationpluginhomeconnect.cpp
> +        qCDebug(dcHomeConnect()) << "HomeConnect url:" << url;
is this printing the api key to the log?

2020-10-22 17:56 UTC, mzanetti commented on homeconnect/integrationpluginhomeconnect.cpp
> +        qCDebug(dcHomeConnect()) << "Redirect url is" << secret;
same... please avoid printing sensitive data to the log. Ideally you'd obfuscate sensitive information but still keep a debug print with enough data to be useful for debugging. I know, it's a bit of extra efford... But it pays back when you don't have to play log-ping-pong with users.

2020-10-22 17:56 UTC, mzanetti commented on homeconnect/integrationpluginhomeconnect.cpp
> +        qCDebug(dcHomeConnect()) << "Authorization code" << authorizationCode;
:)

2020-10-22 17:56 UTC, mzanetti commented on homeconnect/integrationpluginhomeconnect.cpp
> +        HomeConnect *homeConnect = new HomeConnect(hardwareManager()->networkManager(), clientKey, clientSecret, simulationMode, this);
reconfigure case not respected... This will leak on reconfigure...

2020-10-22 17:56 UTC, mzanetti commented on homeconnect/integrationpluginhomeconnect.cpp
> +        m_setupHomeConnectConnections.insert(info->thingId(), homeConnect);
to be precise, this is the line that leaks on reconnect as you're replacing the old one in the map without deleting it and thus losing all references to it.

Still I'd fix it above where I'd do something like

```
HomeConnect *homeConnect = m_setupHomeConnections.value(info->thingId());
if (!homeConnect) {
  homeConnect *homeConnect = new HomeConnect(...);
  m_setupHomeConnections.insert(info->thingId(), homeConnect);
}
```

and just remove the insert here...

2020-10-22 17:56 UTC, mzanetti commented on homeconnect/integrationpluginhomeconnect.cpp
> +        connect(homeConnect, &HomeConnect::authenticationStatusChanged, this, [info, this](bool authenticated){
I think this might mess stuff up on reconfigure as an existing homeConnect object would keep being connected to this lambda until destroyed. So a reconfigure would connect it a second time.

One easy fix would be to use `info` as the third argument instead of `this`, then this connection would vanish when the setup finishes and a reconfigure can just reconnect it again when needed.

2020-10-22 17:56 UTC, mzanetti commented on homeconnect/integrationpluginhomeconnect.h
> +    PluginTimer *m_pluginTimer5sec = nullptr;
seems unused, isn't it?

2020-10-22 17:56 UTC, mzanetti commented on homeconnect/integrationpluginhomeconnect.cpp
> +        //TBD Set user name
I've checked the home connect api and there doesn't seem to be any user info either...

Strange thing is that virtually in all apis I've worked with so far, such an info was available. However, given that it apparently isn't I'm tempted to make the userDisplayName state in the account interface optional. WDYT?

2020-10-22 17:56 UTC, mzanetti commented on homeconnect/integrationpluginhomeconnect.cpp
> +               (thing->thingClassId() == cookTopThingClassId)) {
couldn't you just use `if (m_idParamTypesMap.contains(info->thing()->thingClassId())` instead?

2020-10-22 17:56 UTC, mzanetti commented on homeconnect/integrationpluginhomeconnect.cpp
> +                result->finish(Thing::ThingErrorNoError);
I don't see you actually adding the result here, are you? wouldn't this even crash?

result->item() is a nullptr until you set it. And if you return NoError you should really set it.

Try to create a rule where you run a browser entry. Then edit this rule and see if stuff works.

2020-10-22 17:56 UTC, mzanetti commented on homeconnect/integrationpluginhomeconnect.cpp
> +    }
Ist das Kunst oder kann das weg?

2020-12-04 16:35 UTC, mzanetti requested changes

2020-12-04 16:35 UTC, mzanetti commented on homeconnect/integrationpluginhomeconnect.cpp
> +            qCDebug(dcHomeConnect()) << "Conrol scope is enabled";
typo control

2020-12-04 16:35 UTC, mzanetti commented on homeconnect/integrationpluginhomeconnect.cpp
> +        qCWarning(dcHomeConnect()) << "Unhandled pairing metod!";
typo method

2020-12-04 16:35 UTC, mzanetti commented on homeconnect/integrationpluginhomeconnect.cpp
> +            info->finish(Thing::ThingErrorSetupFailed);
missing return here?

2020-12-04 16:35 UTC, mzanetti commented on homeconnect/integrationpluginhomeconnect.cpp
> +        if (m_setupHomeConnectConnections.keys().contains(thing->id())) {
will this behave properly on reconfiguration? Wouldn't you need to do the stuff below in that case?

2020-12-04 16:35 UTC, mzanetti commented on homeconnect/integrationpluginhomeconnect.cpp
> +        connect(homeConnect, &HomeConnect::connectionChanged, this, &IntegrationPluginHomeConnect::onConnectionChanged);
this on the other hand should probably not be done in the reconfigure case, should it?

2020-12-04 16:35 UTC, mzanetti commented on homeconnect/integrationpluginhomeconnect.cpp
> +                result->item().setDisplayName(result->item().id());
item() returns a copy of the BrowserItem... calling setDisplayName() will vanish into nirvana.
You do need to create a BrowserItem and call info->finish(item) with it.

2020-12-07 09:43 UTC, Boernsman commented on homeconnect/integrationpluginhomeconnect.cpp
> +        if (m_setupHomeConnectConnections.keys().contains(thing->id())) {
Since a reconfigure is now envoking the removeThing method there should be no difference to a ordinary setup

2020-12-07 11:46 UTC, mzanetti commented on homeconnect/integrationpluginhomeconnect.cpp
> +        if (m_setupHomeConnectConnections.keys().contains(thing->id())) {
erm, no, we changed the reconfigure to *not* invoke removeThing any more

2020-12-07 13:24 UTC, Boernsman commented on homeconnect/integrationpluginhomeconnect.cpp
> +        if (m_setupHomeConnectConnections.keys().contains(thing->id())) {
I was pretty sure we agreed to invoke removeThing on reconfigure. If remove thing is not available for cleaning up, then I guess more plug-in are leaking currently.

2020-12-11 16:03 UTC, mzanetti requested changes

2020-12-11 16:03 UTC, mzanetti commented on homeconnect/integrationpluginhomeconnect.cpp
> +        HomeConnect *homeConnect = new HomeConnect(hardwareManager()->networkManager(), clientKey, clientSecret, simulationMode, this);
Hmm... I think this is still not ok...

So on a reconfigure the startPairing() is called again and in that case we already have a homeConnect object in the list which would be lost here, respectively in line 184 where this new one is inserted in the hash without cleaning up the old one... 

You do the check in setupThing() now and delete the existing one there...

So this seems like on a first-time setup, you create 2 of the homeConnect objects, one for pairing and one for operation. No leaks there, but also not needed to destroy the one from the pairing I guess...

On a reconfigure instead, it seems you're leaking the old one, and then additionally create 2 new ones (one for pairing, one for operation).

2020-12-23 22:12 UTC, merged