New plugin: somfytahoma
nymea/nymea-plugins pull request #308
Opened 2020-08-23 15:12 UTC by fetzerch

Add support for controlling Somfy smart home devices through their
Tahoma box (and the Somfy API).

The plugin currently contains support for roller shutters as well as
for venetian blinds.

---

nymea-plugins pull request checklist:

- [x] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [x] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [x] Did you update the plugin's README.md accordingly?

- [x] Did you update translations (`cd builddir && make lupdate`)?

- [x] If you added a new plugin, should it be added to nymea-plugins-all or ~nymea-plugins-maker~?

2020-09-06 01:45 UTC, mzanetti requested changes
Looks quite good. There's an issue with the meta.json / logo.
It refers to somfy.svg but there's a somfy.png.

Ideally you'd provide a svg

2020-09-08 17:08 UTC, mzanetti commented on somfytahoma/somfytahoma.pro
> +include($$[QT_INSTALL_PREFIX]/include/nymea/plugin.pri)
can you include ../plugin.pri instead please in here

2020-09-08 17:25 UTC, fetzerch commented on somfytahoma/somfytahoma.pro
> +include($$[QT_INSTALL_PREFIX]/include/nymea/plugin.pri)
sure, done

2020-09-08 17:25 UTC, fetzerch commented
I've updated the change to include the logo as svg instead of png.

2020-10-22 09:55 UTC, mzanetti approved these changes
Ack. Thank you very much.

Will be moved into the testing repository now

2020-11-05 12:50 UTC, merged