New Plugin: Fastcom
nymea/nymea-plugins pull request #313
Opened 2020-09-04 16:27 UTC by mzanetti

nymea-plugins pull request checklist:

- [ ] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [ ] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [ ] Did you update the plugin's README.md accordingly?

- [ ] Did you update translations (`cd builddir && make lupdate`)?

- [ ] If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker?

2020-10-23 13:16 UTC, Boernsman requested changes
Readme, meta.json, fastcom.png and translation files are missing

2020-10-23 13:16 UTC, Boernsman commented on fastcom/integrationpluginfastcom.json
> +                                    "type": "double",
A bit confusing without any unit. Mbps, MBs, kBs ..

2020-10-23 13:17 UTC, mzanetti commented on fastcom/integrationpluginfastcom.json
> +                                    "type": "double",
ah right... yeah... we're lacking a unit for that still...

2020-10-23 13:26 UTC, mzanetti commented on fastcom/integrationpluginfastcom.json
> +                                    "type": "double",
added readme meta and icon

2020-10-23 14:06 UTC, t-mon requested changes

2020-10-23 14:06 UTC, t-mon commented on fastcom/integrationpluginfastcom.py
> +        runTest(info.thing, duration=info.paramValue(speedtestRunTestActionDurationParamTypeId))
Maybe only run the test if currently no test is running, this could have an impact on both results. Using the state for that would be the easiest way. In case a test is already running, return no error I'd suggest.

2020-10-23 14:21 UTC, Boernsman approved these changes

2020-10-23 15:17 UTC, mzanetti commented on fastcom/integrationpluginfastcom.py
> +        runTest(info.thing, duration=info.paramValue(speedtestRunTestActionDurationParamTypeId))
Fixed... I actually changed to return ThingErrorInUse and a error message that a test is already running which seems more correct IMO

2020-11-05 13:21 UTC, mzanetti commented
merged

2020-11-05 13:21 UTC, closed without merging