Shelly ota
nymea/nymea-plugins pull request #316
Opened 2020-09-05 23:44 UTC by mzanetti

nymea-plugins pull request checklist:

- [ ] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [ ] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [ ] Did you update the plugin's README.md accordingly?

- [ ] Did you update translations (`cd builddir && make lupdate`)?

- [ ] If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker?

2020-10-22 14:00 UTC, Boernsman requested changes

2020-10-22 15:11 UTC, mzanetti commented on shelly/integrationpluginshelly.json
> +                            "displayName": "Furmware update status",
fixed

2020-10-23 09:41 UTC, Boernsman approved these changes

2020-11-05 13:06 UTC, mzanetti commented
merged

2020-11-05 13:06 UTC, closed without merging