OpenWeatherMap: Use api key provider api
nymea/nymea-plugins pull request #326
Opened 2020-10-19 10:39 UTC by mzanetti

nymea-plugins pull request checklist:

- [x] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [x] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [x] Did you update the plugin's README.md accordingly?

- [x] Did you update translations (`cd builddir && make lupdate`)?

- [x] If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker?

2020-10-22 12:36 UTC, Boernsman requested changes

2020-10-22 12:36 UTC, Boernsman commented on openweathermap/integrationpluginopenweathermap.cpp
> +    query.addQueryItem("appid", apiKeyStorage()->requestKey("openweathermap").data("appid"));
please add a plug-in setting for the API key. So the setting's api key would be taken first, if the key is empty the API Key should be used from the API key Storage.

2020-10-22 12:36 UTC, Boernsman commented on openweathermap/integrationpluginopenweathermap.cpp
>      info->finish(Thing::ThingErrorNoError);
Check if any API key is available

2020-10-23 08:53 UTC, mzanetti commented on openweathermap/integrationpluginopenweathermap.cpp
> +    query.addQueryItem("appid", apiKeyStorage()->requestKey("openweathermap").data("appid"));
done

2020-10-23 08:53 UTC, mzanetti commented on openweathermap/integrationpluginopenweathermap.cpp
>      info->finish(Thing::ThingErrorNoError);
done

2020-10-23 09:40 UTC, Boernsman approved these changes

2020-11-05 12:49 UTC, merged