AQI: Added API key provider
nymea/nymea-plugins pull request #330
Opened 2020-10-21 14:55 UTC by Boernsman

nymea-plugins pull request checklist:

- [] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [ ] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [ ] Did you update the plugin's README.md accordingly?

- [ ] Did you update translations (`cd builddir && make lupdate`)?

- [ ] If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker?

2020-10-22 18:05 UTC, mzanetti requested changes
One issue spottet (I believe) and 2 tiny suggestions

2020-10-22 18:05 UTC, mzanetti commented on aqi/integrationpluginaqi.cpp
> +                m_aqiConnection->setApiKey(value.toString());
uhmm... Wouldn't this crash if you set the API without actually having a AQI thing set up?

2020-10-22 18:05 UTC, mzanetti commented on aqi/integrationpluginaqi.json
> +            "displayName": "API key",
"Custom API key" would IMO be better to make it clearer that there is one that should work normally...

2020-10-23 08:28 UTC, Boernsman commented on aqi/integrationpluginaqi.cpp
> +                m_aqiConnection->setApiKey(value.toString());
No, since there is a check if m_aqiConnection is not a nullptr

2020-10-23 08:32 UTC, mzanetti commented on aqi/integrationpluginaqi.cpp
> +                m_aqiConnection->setApiKey(value.toString());
Are you really sure about that?

How I read this code it seems to be a nullptr when neither setupThing() nor discoverThings() has been called, which might be the case on a fresh startup where no AQI things are configured.

2020-10-23 08:44 UTC, mzanetti commented on aqi/integrationpluginaqi.cpp
> +                m_aqiConnection->setApiKey(value.toString());
stupid me... I missed the check for the valid aqiConnectiono in the if...

2020-10-23 08:44 UTC, mzanetti approved these changes
happroved

2020-11-05 12:49 UTC, merged