Tado: Added dynamic API credentials optaining
nymea/nymea-plugins pull request #332
Opened 2020-10-27 12:09 UTC by Boernsman

nymea-plugins pull request checklist:

- [ ] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [ ] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [ ] Did you update the plugin's README.md accordingly?

- [ ] Did you update translations (`cd builddir && make lupdate`)?

- [ ] If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker?

2020-12-04 15:37 UTC, mzanetti requested changes

2020-12-04 15:37 UTC, mzanetti commented on tado/integrationplugintado.cpp
> +            });
fancy, but nice :)

2020-12-04 15:37 UTC, mzanetti commented on tado/tado.cpp
> +            qDebug(dcTado()) << "Get Token: Received invalide JSON object:" << data;
typo, invalid

2020-12-04 15:37 UTC, mzanetti commented on tado/tado.cpp
> +        emit apiCredentialsReceived();
Hmm... so in case of an error happening you just return without emitting anything. AFAICT this will lead the setup to just timeout without providing a proper error. Could you perhaps pass a success/failure flag up and finish() the setup accordingly?

2020-12-07 12:39 UTC, mzanetti commented on tado/tado.cpp
> +            qDebug(dcTado()) << "Get Token: Received invalide JSON object:" << data;
you didn't fix the typo

2020-12-07 12:40 UTC, mzanetti commented on tado/tado.cpp
> +            qDebug(dcTado()) << "Get Token: Received invalide JSON object:" << data;
got fooled by github... all good

2020-12-07 12:43 UTC, mzanetti commented on tado/tado.cpp
> +        emit apiCredentialsReceived();
Is this fixed? Did I get it wrong? AFAICT still an issue, no?

2020-12-09 12:07 UTC, Boernsman commented on tado/tado.cpp
> +        emit apiCredentialsReceived();
this is fixed, added bool success state in signal

2020-12-23 22:12 UTC, merged