Netatmo: Add api key provider and custom api plugin settings
nymea/nymea-plugins pull request #341
Opened 2020-11-02 14:03 UTC by Boernsman

nymea-plugins pull request checklist:

- [ ] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [ ] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [ ] Did you update the plugin's README.md accordingly?

- [ ] Did you update translations (`cd builddir && make lupdate`)?

- [ ] If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker?

2020-12-04 16:46 UTC, mzanetti requested changes
I believe there's on issue to be fixed, at least to be verified.

2020-12-04 16:46 UTC, mzanetti commented on netatmo/integrationpluginnetatmo.cpp
> +        info->finish(Thing::ThingErrorAuthenticationFailure, QT_TR_NOOP("Client credentials are not set."));
I personally find this message a bit misleading... If I read this I'd expect something wrong with the stuff I entered but not with the setup. Dunno, maybe it's just me. Just brainstorming: From an end user point of view, what would be the thing that makes you understand what's actually going on? Something like "No API key installed" perhaps? I don't like API key in a end user context as it seems too technical, client credentials seems to unspecific tho to know what to look for... I think the "not installed" part would be good tho as it lets the user know that something needs installing?

Dunno... I'll leave it up to you... just some general thoughts.

2020-12-04 16:52 UTC, Boernsman commented on netatmo/integrationpluginnetatmo.cpp
> +    connect(info, &ThingPairingInfo::aborted, authentication, &OAuth2::deleteLater);
If the authentication was successfull the authentication object will now be forwareded to the thing setup. It is intended to delete the object only on failure

2020-12-04 17:24 UTC, mzanetti approved these changes

2020-12-09 09:32 UTC, Boernsman commented on netatmo/integrationpluginnetatmo.cpp
> +    connect(info, &ThingPairingInfo::aborted, authentication, &OAuth2::deleteLater);
reworked the reconfiguration, no all memory leaks should be fixed

2020-12-09 09:36 UTC, Boernsman commented on netatmo/integrationpluginnetatmo.cpp
> +        info->finish(Thing::ThingErrorAuthenticationFailure, QT_TR_NOOP("Client credentials are not set."));
error message changed to "No API key installed"

2020-12-23 22:12 UTC, merged