Adjust media plugins to new interfaces
nymea/nymea-plugins pull request #351
Opened 2020-11-21 19:20 UTC by mzanetti

nymea-plugins pull request checklist:

- [ ] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [ ] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [ ] Did you update the plugin's README.md accordingly?

- [ ] Did you update translations (`cd builddir && make lupdate`)?

- [ ] If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker?

2020-12-04 17:07 UTC, mzanetti commented
Acking @Boernsman 's changes. Please review mine.

2020-12-09 14:32 UTC, Boernsman requested changes

2020-12-09 14:32 UTC, Boernsman commented on denon/integrationplugindenon.json
> -                            ]
Why do you remove the step size on this thingClass, but added it on other thingClasses (e.g. Heos)

2020-12-09 14:32 UTC, Boernsman commented on denon/integrationplugindenon.json
> -                            ]
I'ld rather add step size to every in-/decrease volume action, I guess this feature is mainly used by building automation integrators and having the possibility to configure the step size on a button press will be handy.

2020-12-11 16:55 UTC, mzanetti commented on denon/integrationplugindenon.json
> -                            ]
thanks for the help. Adjusted min/max checking on top of your commit.

2020-12-29 12:25 UTC, mzanetti commented
merged

2020-12-29 12:25 UTC, closed without merging