WIP: Keba: Rework
nymea/nymea-plugins pull request #374
Opened 2021-01-13 11:19 UTC by Boernsman

nymea-plugins pull request checklist:

- [ ] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [ ] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [ ] Did you update the plugin's README.md accordingly?

- [ ] Did you update translations (`cd builddir && make lupdate`)?

- [ ] If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker?

2021-01-13 11:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nymea/nymea-plugins?pullRequest=374) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/nymea/nymea-plugins?pullRequest=374) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: mzanetti<br/>:white_check_mark: t-mon<br/>:white_check_mark: Boernsman<br/>:x: nymea-jenkins<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nymea/nymea-plugins?pullRequest=374) it.</sub>

2021-01-27 09:02 UTC, t-mon requested changes

2021-01-27 09:02 UTC, t-mon commented on keba/kecontactdatalayer.cpp
> +    connect(m_udpSocket, &QUdpSocket::readyRead, this, &KeContactDataLayer::readPendingDatagrams);
Maybe also handle the error cases for the udp socket to see if something goes wrong during operation

2021-01-29 13:05 UTC, Boernsman commented on keba/kecontactdatalayer.cpp
> +    connect(m_udpSocket, &QUdpSocket::readyRead, this, &KeContactDataLayer::readPendingDatagrams);
Added error handling with debug output

2021-01-29 13:13 UTC, Boernsman commented on keba/integrationpluginkeba.cpp
> +            m_kebaData = new KeContactDataLayer;
added 'this' as parent + deletion on failed setup

2021-02-14 13:44 UTC, mzanetti approved these changes

2021-03-03 22:07 UTC, merged