Shelly: Add support for shelly i3
nymea/nymea-plugins pull request #381
Opened 2021-01-24 19:52 UTC by herbiehp

nymea-plugins pull request checklist:

- [x] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [x] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [x] Did you update the plugin's README.md accordingly?

- [ ] Did you update translations (`cd builddir && make lupdate`)?

- [ ] If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker?

2021-01-24 19:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nymea/nymea-plugins?pullRequest=381) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/nymea/nymea-plugins?pullRequest=381) before we can accept your contribution.<br/>**3** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: t-mon<br/>:white_check_mark: Boernsman<br/>:white_check_mark: mzanetti<br/>:x: simonseres<br/>:x: herbiehp<br/>:x: nymea-jenkins<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nymea/nymea-plugins?pullRequest=381) it.</sub>

2021-01-24 19:54 UTC, herbiehp commented
wrong branch

2021-01-24 19:59 UTC, herbiehp commented
to experimental-silo

2021-01-25 16:14 UTC, mzanetti requested changes
Haven't tested it yet.

You want to add the settings handling in "setupShellyGateway" too

2021-01-25 16:14 UTC, mzanetti commented on shelly/integrationpluginshelly.json
> +                    "name": "shellyix3",
For consistency with other shellies, the i should probably be uppercase... Also, why the "x"?

I just checked the docs, and it seems the i3 does indeed present itself as ix3 on MQTT... Normally we keep the thing class ID closer to the user facing product name... Anyhow, not a big deal, can also stay ix3, still please uppercase the i, so `shellyI3` or `shellyIx3`.

2021-01-25 22:40 UTC, mzanetti commented on shelly/integrationpluginshelly.cpp
> +           thing->emitEvent(shellyI3PressEventTypeId, ParamList() << Param(shellyI3PressEventOriginParamTypeId, QString::number(channel +1)));
AFAICT you should not emit an event here, but instead something like this:
```
QHash<int, StateTypeId> channelMap = {
  {0, shellyI3Input1StateTypeId},
  {1, shellyI3Input2StateTypeId},
  {2, shellyI3Input3StateTypeId},
};
thing->setStateValue(channelMap.value(channel), on);
```
And drop the "press" event from the json

2021-01-25 22:40 UTC, mzanetti commented on shelly/integrationpluginshelly.json
> +                            "id": "724d18ff-693b-4a9c-aa72-66557e0069d6",
As discussed in the chat, I think we don't need this eventType. Instead the input1/2/3 stateTypes will cater for this.

2021-01-25 22:42 UTC, mzanetti commented on shelly/integrationpluginshelly.cpp
> +        if (thing->thingClassId() == shellyButton1ThingClassId) {  // it can be only at channel 0
Also I think you can move the `int channel` from above down into the if (shellyI3ThingClassId). No need to parse the channel from the topic if it can be only 0 for the button1 anyways

2021-01-25 23:37 UTC, herbiehp commented on shelly/integrationpluginshelly.json
> +                            "id": "724d18ff-693b-4a9c-aa72-66557e0069d6",
done

2021-01-25 23:39 UTC, herbiehp commented on shelly/integrationpluginshelly.cpp
> +        if (thing->thingClassId() == shellyButton1ThingClassId) {  // it can be only at channel 0
moved

2021-01-25 23:40 UTC, herbiehp commented on shelly/integrationpluginshelly.json
> +                    "name": "shellyix3",
it is shellyI3 now

2021-02-14 13:51 UTC, mzanetti commented
@herbiehp please update the translations:

build it as normally, then go to the *plugins* build directory and run make lupdate:
```
cd builddir/shelly
make lupate
```

2021-02-14 13:52 UTC, mzanetti commented
apart from that, the pull request looks good to go

2021-02-17 16:05 UTC, herbiehp commented
> @herbiehp please update the translations:
> 
> build it as normally, then go to the _plugins_ build directory and run make lupdate:
> 
> ```
> cd builddir/shelly
> make lupate
> ```

completed

2021-02-17 16:37 UTC, mzanetti approved these changes
Thanks! Approved

2021-03-03 22:07 UTC, merged