New Plugin: ZigbeeDevelco
nymea/nymea-plugins pull request #422
Opened 2021-04-28 11:07 UTC by t-mon

nymea-plugins pull request checklist:

- [ ] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [ ] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [ ] Did you update the plugin's README.md accordingly?

- [ ] Did you update translations (`cd builddir && make lupdate`)?

- [ ] If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker?

2021-06-27 18:02 UTC, mzanetti requested changes
Mostly fine, just some little comments.

2021-06-27 18:02 UTC, mzanetti commented on zigbeedevelco/integrationpluginzigbeedevelco.cpp
> +    connect(reply, &ZigbeeClusterReply::finished, node, [=](){
Are we positive that basicCluster and endpoint will *always* exist longer than any replies finished() signal? I suppose yes, just asking as I'm not 1000% sure and the lambda capture seems very lax... (In such a place where you have a lot of member veriables, I'd kinda prefer to just capture what's really needed instead (actually only `[reply]` unless we really want endpoint and all in the warning) of the whole context with [=]...

2021-06-28 07:25 UTC, t-mon commented on zigbeedevelco/README.md
> +In order to bring a ZigBee device into the nymea ZigBee network, the network needs to be opened for joining before you perform the device pairing instructions. The joining process can take up to 30 s
There is the list, right after this section, but one is missing, adding it.

2021-06-28 09:43 UTC, mzanetti approved these changes

2021-07-08 23:30 UTC, merged