WakeOnLan: Add network device discovery
nymea/nymea-plugins pull request #442
Opened 2021-06-04 22:26 UTC by t-mon

nymea-plugins pull request checklist:

- [ ] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [ ] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [ ] Did you update the plugin's README.md accordingly?

- [ ] Did you update translations (`cd builddir && make lupdate`)?

- [ ] If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker?

2021-06-27 20:13 UTC, mzanetti requested changes
Minor nitpicks. Mostly fine.

2021-06-27 20:13 UTC, mzanetti commented on wakeonlan/integrationpluginwakeonlan.cpp
> +        info->finish(Thing::ThingErrorHardwareNotAvailable, QT_TR_NOOP("The discovery is not available."));
This isn't a very user friendly error message... IMO something like "Unable to discovery devices in your network." would be better for an end user. This one is fine for a warning message in the logs.

2021-06-27 20:13 UTC, mzanetti commented on wakeonlan/integrationpluginwakeonlan.cpp
> +    qCDebug(dcWakeOnLan()) << "Start discovering network devices...";
"Starting network discovery..."

2021-06-27 20:13 UTC, mzanetti commented on wakeonlan/integrationpluginwakeonlan.cpp
> +            // Filter out already added network devices, rediscovery is in this case no option
Hmm... Why preventing the rediscovery? I agree it doesn't make sense, but the API allows to do it so IMO it should return something sensible.

2021-06-27 20:13 UTC, mzanetti commented on wakeonlan/integrationpluginwakeonlan.cpp
> +            // Filter out already added network devices, rediscovery is in this case no option
Would be enough to change the code like this I guess:

```
Thing *existingThing = myThings().findByParam(Param(wolThingMacParamTypeId, networkDeviceInfo.macAddress());
if (existingThing) {
    descriptor.setThingId(existingThing->id());
}
```

2021-06-28 07:41 UTC, t-mon commented on wakeonlan/integrationpluginwakeonlan.cpp
> +            // Filter out already added network devices, rediscovery is in this case no option
The idea was: if you reconfigure this thing, you probably wanna change the mac address, if not, add a new one, yes, but a rediscovery and showing only the one you already added makes no sense, that's why I didn't wanted to set the existing id...

2021-06-28 09:13 UTC, mzanetti commented on wakeonlan/integrationpluginwakeonlan.cpp
> +            // Filter out already added network devices, rediscovery is in this case no option
I see it mostly like a "Hmm... something didn't seem to work, lemme try reconfiguring it". And then the user goes to reconfigure and reconfigure doesn't work either...

2021-07-08 23:30 UTC, merged