New plugin: Yamaha network receiver
nymea/nymea-plugins pull request #459
Opened 2021-07-30 12:49 UTC by loosrob

add control for (non-Musiccast) Yamaha network receivers

nymea-plugins pull request checklist:

- [x] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [x] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [x] Did you update the plugin's README.md accordingly?

- [x] Did you update translations (`cd builddir && make lupdate`)?

- [x] If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker?

2021-07-30 13:02 UTC, t-mon commented
Awesome!

2021-08-17 14:30 UTC, mzanetti requested changes

2021-08-17 14:30 UTC, mzanetti commented on debian/control
> +         Nymea-plugin-yamaha,
We have an issue in our builders still that prevents us to pre-install python plugins on the images. So this should be removed. You can add it to the "nymea-plugins-all" meta package tho. 

And the uppercase N is a typo that would fail the builders too.

2021-08-30 15:43 UTC, mzanetti approved these changes

2021-09-02 16:02 UTC, mzanetti approved these changes

2021-09-18 20:59 UTC, merged