New plugin: garadget
nymea/nymea-plugins pull request #501
Opened 2021-10-30 18:09 UTC by hi-flyer

nymea-plugins pull request checklist:

- [ ] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [ ] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested. - yes

- [ ] Did you update the plugin's README.md accordingly? yes

- [ ] Did you update translations (`cd builddir && make lupdate`)? yes

- [ ] If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker? Unsure of which is correct one to chose. I am only intentionally adding the garadget plugin.

2021-10-30 19:48 UTC, mzanetti requested changes
The plugin code itself looks pretty solid. Great work and thank you very much for your contribution!

What's a bit odd is (and that goes on us) that you've updated all the translations (.ts files) for all the plugins. This will cause conflicts with other pull requests. Instead you should've done this only inside the garadget subdirectory of the build directory.
I should make the todo list more clear on that. Sorry. Once this is reverted, I can include the plugin into the experimental repository.

Also the garadget/debian directory is not needed when integrating the plugin into the nymea-plugins repository (this would only be needed if we'd keep it as a standalone plugin in its own repository). You've done the changes in the top level debian/ directory properly, so you can just delete the garadget/debian.

2021-10-30 19:48 UTC, mzanetti commented on garadget/LICENSE.LGPL3
> +                   GNU LESSER GENERAL PUBLIC LICENSE
Please remove this file. There's one already in the top level of the nymea-plugins directory.

2021-10-30 19:48 UTC, mzanetti commented on garadget/README.md
> +The NYMEA plugin for Garadget Garage Door Opener requires Garadget version 1.20 or later
nymea should be written as "nymea" (all lowercase) even when starting a senctence with it. However, in order to avoid weird looking sentences we try to avoid starting with it, if possible.

2021-10-30 19:48 UTC, mzanetti commented on garadget/README.md
> +
I suppose it would make sense to add a small note saying something like:
Make sure nymeas MQTT broker is enabled in System Settings -> MQTT broker and create a policy (Client ID, username and password) for the garadget device to log in. Alternatively, authentication on the MQTT broker may be disabled (not recommended).

2021-10-30 19:48 UTC, mzanetti commented on garadget/README.md
> +        enter NYMEAD Broker Port:
And I suppose the garadget would also support entering the clientId, username and passwort for a policy created in my previous comment, would it?

2021-10-30 19:48 UTC, mzanetti commented on garadget/README.md
> +    The plugin does NOT know if the Garadget disconnects and therefore will continue to show connected even if the Garadget is no longer connected.
Does the garadget device allow setting a "last will" in the MQTT settings? If so, you could add a lastwill message there and process it in the plugin.

2021-10-30 19:48 UTC, mzanetti commented on garadget/debian/changelog
> +nymea-plugin-Garadget (0.0.1) xenial; urgency=medium
This one is not needed when integrating the plugin into the bigger nymea-plugins package. It will use the changelog file from nymea-plugins/debian/changelog (on the top level of the plugins repo) instead. You can just delete this file.

2021-10-30 19:48 UTC, mzanetti commented on garadget/debian/compat
> +9
Same here, can delete this one

2021-10-30 19:48 UTC, mzanetti commented on garadget/debian/control
> +Source: nymea-plugin-garadget
same, delete this

2021-10-30 19:48 UTC, mzanetti commented on garadget/debian/copyright
> +Format: http://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
in fact, the whole "garadget/debian/" folder can just go away

2021-10-30 19:48 UTC, mzanetti commented on garadget/meta.json
> +        "socket"
hmm... socket doesn't seem to be a good fit, does it? The categories field will specify where the plugin is listed on https://nymea.io/documentation/resources/integrations

"lock" seems the most appropriate IMO.

2021-10-31 10:42 UTC, hi-flyer commented
reset code to earlier version with changes requested. will create new pull request.

2021-10-31 10:42 UTC, closed without merging