New plugin: Garadget
nymea/nymea-plugins pull request #502
Opened 2021-10-31 11:39 UTC by hi-flyer

nymea-plugins pull request checklist:

- [ ] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested. Yes

- [ ] Did you update the plugin's README.md accordingly? Yes and modified as suggested

- [ ] Did you update translations (`cd builddir && make lupdate`)? yes for garadget only this time!

- [ ] If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker? I do not know the correct answer for this one.
- [ ] git reset suggested did not remove all unwanted commits. I deleted the branch and recreated it adding all updates. So this should be the modified version for the plugin.

2021-10-31 12:22 UTC, mzanetti commented on garadget/integrationplugingaradget.json
> +                            "id": "024f178c-a920-42d4-887f-1c90a96d5eb3",
If you add the "wirelessconnectable" interface and rename this state to "signalStrength", nymea:app will show the signal strength icon in the UI.

2021-10-31 12:22 UTC, mzanetti commented on garadget/integrationplugingaradget.json
> +                            "name": "brightlevel",
Also here you can add the "lightsensor" interface and rename the state to "lightIntensity" and nymea:app will show it in the sensors section for a light sensor too.

2021-10-31 12:22 UTC, mzanetti commented on garadget/integrationplugingaradget.json
> +                            "name": "sensorlevel",
What sort of sensor is this?

2021-10-31 12:22 UTC, mzanetti commented on garadget/integrationplugingaradget.json
> +                            "displayName": "Button Press Time in 10-2000 ms",
Wouldn't this make more sense as a settingTypes instead of a stateTypes?

2021-10-31 12:22 UTC, mzanetti commented on garadget/integrationplugingaradget.json
> +                            "name": "mtt",
Same here, seems to be more of a setting instead of a state, no?

2021-10-31 12:26 UTC, mzanetti commented
@nymea-jenkins test this please

2021-10-31 12:41 UTC, hi-flyer commented
so what was the correct answer to this one? should it be added to nymea-plugins-all or nymea-plugins-maker?

2021-10-31 12:43 UTC, mzanetti commented
> so what was the correct answer to this one? should it be added to nymea-plugins-all or nymea-plugins-maker?

yes, to nymea-plugins-all

2021-10-31 18:08 UTC, hi-flyer commented on garadget/integrationplugingaradget.json
> +                            "id": "024f178c-a920-42d4-887f-1c90a96d5eb3",
I did implement this but am rejecting as I do not see a good reason to implement. I did not see the icon you talk about and further, this assumes a percentage level. while I can trick it to a number between 0 and 100, it is really an rssi value if I understand it correctly. It is there, in my opinion to help the user know that the device has a good connection to the wifi access point. Also I did not understand how I could set this value when received from garadget.

2021-10-31 18:16 UTC, hi-flyer commented on garadget/integrationplugingaradget.json
> +                            "name": "sensorlevel",
The light sensor mentioned above is used to detect the lazed beam reflected off of the garage door or wall depending on where you put the reflector. Modification of the value associate with this level helps eliminate false detected state changes. the value of this does change depending on the value of the brightness level. so to summarize it is a calculated value of the reflected lazer signal level. I did not read this anywhere but that is what it is.

2021-10-31 18:19 UTC, hi-flyer commented on garadget/integrationplugingaradget.json
> +                            "displayName": "Button Press Time in 10-2000 ms",
tried to modify this but did not see a way to set it based on the returned values from the garadget device. Ok, I struggle with QT and did not find anything on how to set the value if changed to settingsType.

2021-10-31 18:19 UTC, hi-flyer commented on garadget/integrationplugingaradget.json
> +                            "name": "mtt",
same as above, tried to modify this but did not see a way to set it based on the returned values from the garadget device. Ok, I struggle with QT and did not find anything on how to set the value if changed to settingsType.

2021-10-31 18:21 UTC, hi-flyer commented
responded to mzanetti suggestions above.

2021-11-01 11:20 UTC, hi-flyer commented on garadget/integrationplugingaradget.json
> +                            "id": "024f178c-a920-42d4-887f-1c90a96d5eb3",
I have made the change in my test unit but do not see any change in the UI.

2021-11-01 11:22 UTC, hi-flyer commented on garadget/integrationplugingaradget.json
> +                            "name": "sensorlevel",
I am change the display name to Laser Sensor Level to help user understand.

2021-11-01 13:48 UTC, mzanetti commented
Fails the build. `garadget` is missing in nymea-plugins.pro so it won't be built and the packaging complains about it being missing,

2021-11-01 14:06 UTC, mzanetti commented on garadget/integrationplugingaradget.json
> +                            "id": "024f178c-a920-42d4-887f-1c90a96d5eb3",
rssi to percentage:
percentage = (rssi + 50) / 100

2021-11-01 14:08 UTC, mzanetti commented on garadget/integrationplugingaradget.json
> +                            "id": "024f178c-a920-42d4-887f-1c90a96d5eb3",
About the icon you're not seeing: That really must be working, it's being used by tons of other plugins. Can you show the changes you made? there must be a little mistake somewhere.

2021-11-01 14:09 UTC, mzanetti commented on garadget/integrationplugingaradget.json
> +                            "name": "sensorlevel",
oh, I see. Yes, in this case it's not an acutal lightSensor. Fine to not use that interface for this then.

2021-11-01 14:10 UTC, mzanetti commented on garadget/integrationplugingaradget.json
> +                            "displayName": "Button Press Time in 10-2000 ms",
You can call `thing->setSettingsValue(<typeId>, <value>)` to update the settings value programmatically.

2021-11-01 14:10 UTC, mzanetti commented on garadget/integrationplugingaradget.json
> +                            "name": "mtt",
thing->setSettingsType()

2021-11-03 13:16 UTC, hi-flyer commented
Have installed experimental on my Ubuntu 20.04 version. When I try to activate it, it shows uh oh, something when wrong. I compilied my latest version, that I uploaded this morning on Ubuntu 20.04 and placed libnymea_integrationplugingaradget.so on the operational system and it works as designed. not sure what the problem is with the experimental

2021-11-03 14:05 UTC, mzanetti commented
> not sure what the problem is with the experimental

The package in the experimental has a build timestamp in the version. It will only include your changes that have been pushed before that time (It's in UTC). So depending on when you pushed your changes and when we've triggered a build for the repository, it may or may not contain your latest changes.

That said, checking the logs during the setup should also help with finding out what's going on.

2021-11-03 15:15 UTC, hi-flyer commented
I have removed garadget and reinstalled but now the garadget does not show up on the config menu. tried multiple times. The Nov 2 version (according to the date on the file) is what it installs. nothing showing in the nymea logs from the main log viewer.

2021-11-03 17:41 UTC, mzanetti commented on garadget/integrationplugingaradget.cpp
> +            if (m_garadgetconnect == 1) {
I don't understand why this if(m_garadgetconnect == 1). Seems like the timer should publish the get-status unconditionally to every configured garadget system, no?

2021-11-03 17:41 UTC, mzanetti commented on garadget/integrationplugingaradget.cpp
> +            if ((timesinceupdate > updatetime) && (m_garadgetconnect == 1)) {
A leaner way of checking how much time passed would be:
```
if (m_lastiActivityTimeStamps[thing].msecsTo(QDateTime::currentDateTime()) > updateTime) { ... }
```

Again, not sure why the m_garadgetconnect == 1

2021-11-03 17:41 UTC, mzanetti commented on garadget/integrationplugingaradget.cpp
> +                m_garadgetconnect = 0;
The biggest issue with the m_garadgetconnect is that you only store one. If a user has multiple garadgets connected, this will break because the two (or more) will overwrite each other's m_garadgetconnect.

2021-11-03 17:41 UTC, mzanetti commented on garadget/integrationplugingaradget.cpp
> +            m_garadgetconnect = 1;
if this is just about memorizing the connected status, you might as well read the things statevalue with

```
thing->stateValue(garadgetConnectedStateTypeId).toBool()
```
This will return what you've last set to it. I.e. it will be in sync with your m_garadgetconnect variable and has the additional benefit that it will also work with multiple.

Anyhow, still not sure why it's needed at all.

2021-11-03 17:41 UTC, mzanetti commented on garadget/integrationplugingaradget.cpp
> +    m_lastActivityTimeStamps[thing] = QDateTime::currentDateTime();
I wouldn't even initialize it here. Because when the system starts up, you haven't ever heard from the device, you don't know if it's connected so it's wise to assume it is not connected at this point.

2021-11-03 17:41 UTC, mzanetti commented on garadget/integrationplugingaradget.cpp
> +        m_pluginTimer = nullptr;
Generally, good that you've thought of cleaning up. However, current code suffers from the issue that if you add 2 garadget devices, and then remove one of them, the timer will be removed even though it would still be needed.

Easy fix: just add this to the if statement:
```
if (m_pluginTimer && myThings().isEmpty())
```

2021-11-03 17:44 UTC, hi-flyer commented on garadget/integrationplugingaradget.cpp
> +            if (m_garadgetconnect == 1) {
if I get a disconnect, it continues to publish a get-status which It should not do if garadget is not on line. Garadget publishes it status when it comes online automatically.

2021-11-03 18:01 UTC, hi-flyer commented on garadget/integrationplugingaradget.cpp
> +            if (m_garadgetconnect == 1) {
this gets into your later comment on m_garadgetconnect. It needs to check the status of each garadget. will work on.

2021-11-03 18:25 UTC, hi-flyer commented on garadget/integrationplugingaradget.cpp
> +            if (m_garadgetconnect == 1) {
have removed m_garadgetconnect an use the state now as suggested below. Still believe that it should not request status if it is not online. so moved if inside the foreach.

2021-11-03 19:08 UTC, hi-flyer commented on garadget/integrationplugingaradget.cpp
> +                m_garadgetconnect = 0;
m_garadgetconnect is removed

2021-11-03 19:12 UTC, hi-flyer commented on garadget/integrationplugingaradget.cpp
> +            m_garadgetconnect = 1;
m_garadgetconnect is now gone. I assume this solves your comment.

2021-11-03 19:12 UTC, hi-flyer commented on garadget/integrationplugingaradget.cpp
> +    m_lastActivityTimeStamps[thing] = QDateTime::currentDateTime();
accepted. it is now gone

2021-11-03 19:19 UTC, hi-flyer commented on garadget/integrationplugingaradget.cpp
> +        m_pluginTimer = nullptr;
needed !myThing().isEmpty()
done

2021-11-03 20:59 UTC, hi-flyer commented on garadget/integrationplugingaradget.json
> +                            "displayName": "Button Press Time in 10-2000 ms",
reflection threshold and the sensor level are related. Want to see them on the same page from a user prospective. so not making this suggested change.

2021-11-03 21:01 UTC, hi-flyer commented on garadget/integrationplugingaradget.json
> +                            "name": "mtt",
note that reflection threshold needs to be on the same page as the Lazer sensor level. moving this to the settings page does not make sense in this case to me.

2021-11-04 20:42 UTC, mzanetti requested changes

2021-11-04 20:42 UTC, mzanetti commented on garadget/integrationplugingaradget.cpp
> +    if (!(device.startsWith( "garadget/"))) {
To be hones I would just assume the user does *not* add "garadget/" and automatically do that in here... AFAIK it's also just "deviceName" in the garadget's settings, so if nymea asks for the device name, why would someone add "garadget/" to it?

2021-11-04 20:42 UTC, mzanetti commented on garadget/integrationplugingaradget.cpp
> +        thing->setParamValue(garadgetThingDeviceNameParamTypeId,"garadget/" + device + "/#" );
It's kinda bad practice to overwrite the parameters the user has set... Yes, it's possible, but if not absolutely required, we try to avoid that as it is confusing for the user.

2021-11-04 20:42 UTC, mzanetti commented on garadget/integrationplugingaradget.cpp
> +    if (thing->thingClassId() == garadgetThingClassId) {
why this if? Seems it's always true. Could just go aways IMO

2021-11-04 20:42 UTC, mzanetti commented on garadget/integrationplugingaradget.cpp
> +    if (thing->thingClassId() == garadgetThingClassId) {
again, the if here doesn't seem to be necessary. Given there is only one ThingClass in this plugin, this if will always be true. Can just go away

2021-11-04 20:42 UTC, mzanetti commented on garadget/integrationplugingaradget.cpp
> +        client->subscribe(thing->paramValue(garadgetThingDeviceNameParamTypeId).toString());
I'd personally do:
```
client->subscribe("garadget/" + thing->paramValue(garadgetThingDeviceNameParamTypeId).toString());
```
As I said before, I'd assume the "garadget/" is not given by the user and would just always prepend it here and be done with it.

2021-11-04 20:42 UTC, mzanetti commented on garadget/integrationplugingaradget.cpp
> +        qCWarning(dcGaradget) << "Received a publish message from a client where de don't have a matching thing" << retained;
typo :) "de" -> "we"

2021-11-04 20:42 UTC, mzanetti commented on garadget/integrationplugingaradget.cpp
> +        m_pluginTimer = nullptr;
This still seems to be a problem. Creating 2 garadget things, and then removing one of them, will break the other

2021-11-04 20:42 UTC, mzanetti commented on garadget/integrationplugingaradget.cpp
> +    if (!m_pluginTimer && !myThings().isEmpty()) {
myThings() will never be empty in a postSetupThing() call. It will always contain at least the one thing that just has been set up.

2021-11-04 20:42 UTC, mzanetti commented on garadget/integrationplugingaradget.cpp
> +        qCDebug(dcGaradget) << "inside m_pluginTimer with" << name ;
Perhaps clean the debug messages a bit up. It's fine to have debug messages, but please make them nice texts and contain informative stuff.

2021-11-04 20:42 UTC, mzanetti commented on garadget/integrationplugingaradget.cpp
> +                    m_mqttClients.value(thing)->publish(name + "/set-config", garadgetdata);
oh, obviously, if you follow my other suggestion about not assuiming the the "garadget/" in the name, then the publish calls would also need to have `"garadget/" + ` prepended. I suppose that's why you added it to the param in the first place, so you don't have to type it every time. Well, nymea philosophy is: The developers goes the extra mile if it's for a better user experience :)

2021-11-04 20:42 UTC, mzanetti commented on garadget/integrationplugingaradget.cpp
> +    return;
Hmm... I can see paths where you end up in this return without having called info->finish(), no? What if there's a srcAction but the param is <= -1 ? "act" wil be empty and info->finish will never be called, no?
This will cause the ui in the app to spin for 30 seconds, waiting on the action to finish and then causing a timeout error.

2021-11-04 20:42 UTC, mzanetti commented on garadget/integrationplugingaradget.cpp
> +    return;
Also, could it perhaps make sense to define "minValue" and "maxValue" for those srt states in the json file?

2021-11-05 19:27 UTC, hi-flyer commented on garadget/integrationplugingaradget.cpp
> +    if (!(device.startsWith( "garadget/"))) {
Ok.

2021-11-05 19:42 UTC, hi-flyer commented on garadget/integrationplugingaradget.cpp
> +    return;
I am aware of the 30 second timeout. was not sure it was appropriate to put info->finish(Thing::ThingErrorNoError); at the end but it is now there. I also point out that if -1 is entered the software will instead send a request for status will reset the user input to what is in the garadget. So I accepted you suggestion.

as far as minValue and maxValue, I did have them in there but that puts a slider up for which it was extremely hard to select the value I was want to enter. therefore I eliminated them to achieve the ability to enter the number I really wanted.

2021-11-05 19:49 UTC, hi-flyer commented on garadget/integrationplugingaradget.cpp
> +                    m_mqttClients.value(thing)->publish(name + "/set-config", garadgetdata);
also requires fix on other places where I took advantage of rename of nameDevice. am changing all places.

2021-11-05 19:51 UTC, hi-flyer commented on garadget/integrationplugingaradget.cpp
> +        qCDebug(dcGaradget) << "inside m_pluginTimer with" << name ;
I meant to remove. It was for me and forgot to remove. gone now.

2021-11-05 20:05 UTC, hi-flyer commented on garadget/integrationplugingaradget.cpp
> +        client->subscribe(thing->paramValue(garadgetThingDeviceNameParamTypeId).toString());
just part of not changing deviceName. accepted but you missed adding "/#" at the end.

2021-11-05 20:06 UTC, hi-flyer commented on garadget/integrationplugingaradget.cpp
> +    if (thing->thingClassId() == garadgetThingClassId) {
accepted

2021-11-05 20:11 UTC, hi-flyer commented on garadget/integrationplugingaradget.cpp
> +    if (thing->thingClassId() == garadgetThingClassId) {
accepted

2021-11-05 20:13 UTC, hi-flyer commented on garadget/integrationplugingaradget.cpp
> +        thing->setParamValue(garadgetThingDeviceNameParamTypeId,"garadget/" + device + "/#" );
ok, am fixing all places where this affects

2021-11-05 20:20 UTC, hi-flyer commented on garadget/integrationplugingaradget.cpp
> +        m_pluginTimer = nullptr;
sorry, but I accommodated one of your previous comments on this to do this but in the wrong spot. now put in the right spot. so comment accepted.

2021-11-05 20:22 UTC, hi-flyer commented on garadget/integrationplugingaradget.cpp
> +    if (!m_pluginTimer && !myThings().isEmpty()) {
this is where I placed  && !myThings().isEmpty() in the wrong spot. I should have put in the thingRemoved section.

accepted

2021-11-05 21:39 UTC, mzanetti approved these changes
LGTM :+1: 

Thanks for the contribution. Will be included in nymea 0.30.

2021-11-13 13:20 UTC, hi-flyer commented
Longer term testing shows false detection of unexpected disconnects. Testing a solution to resolve this issue.

2021-11-18 19:14 UTC, mzanetti requested changes

2021-11-18 19:14 UTC, mzanetti commented on garadget/integrationplugingaradget.cpp
> +            thing->setStateValue(garadgetLWTStateTypeId,true);
I don't think this should be a thing state... it's not of any interest to the user but only an implementation detail. You can store that in the pluginStorage instead:

```
pluginStorage()->beginGroup(thing->id());
pluginStorage()->setValue("lastWillAvailable", true);
pluginStorage()->endGroup();
```

and to read:
```
pluginStorage()->beginGroup(thing->id());
bool lastWillAvailable = pluginStorage()->setValue("lastWillAvailable").toBool();
pluginStorage()->endGroup();
```

2021-11-18 21:56 UTC, hi-flyer commented on garadget/integrationplugingaradget.cpp
> +            thing->setStateValue(garadgetLWTStateTypeId,true);
Agree and have made changes

2021-12-07 16:23 UTC, mzanetti approved these changes

2021-12-16 23:18 UTC, merged