Fronius: Update to latest interface requirements and add providedInterfaces
nymea/nymea-plugins pull request #507
Opened 2021-11-12 16:22 UTC by t-mon

…or the datalogger

nymea-plugins pull request checklist:

- [ ] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [ ] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [ ] Did you update the plugin's README.md accordingly?

- [ ] Did you update translations (`cd builddir && make lupdate`)?

- [ ] If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker?

2021-12-07 19:04 UTC, mzanetti approved these changes

2021-12-10 12:36 UTC, mzanetti requested changes

2021-12-10 12:36 UTC, mzanetti commented on fronius/froniusstorage.cpp
> -    pluginThing()->setStateValue(storageDischargingStateTypeId, charge_akku > 0);
the interface specifies a single state for this.

2021-12-10 12:37 UTC, mzanetti commented on fronius/froniusstorage.cpp
> -    pluginThing()->setStateValue(storageDischargingStateTypeId, charge_akku > 0);
```
        {
            "name": "chargingState",
            "type": "QString",
            "allowdValues": ["idle", "charging", "discharging"],
            "optional": true
        }
```

2021-12-10 12:44 UTC, t-mon commented on fronius/froniusstorage.cpp
> -    pluginThing()->setStateValue(storageDischargingStateTypeId, charge_akku > 0);
fixed

2021-12-10 12:45 UTC, mzanetti commented on fronius/integrationpluginfronius.json
> +                    "interfaces": [ "energystorage"],
accidental?

2021-12-10 12:50 UTC, mzanetti approved these changes

2021-12-16 23:18 UTC, merged