WIP: SMA: Add speedwire interface
nymea/nymea-plugins pull request #517
Opened 2021-12-03 13:17 UTC by t-mon

nymea-plugins pull request checklist:

- [ ] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [ ] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [ ] Did you update the plugin's README.md accordingly?

- [ ] Did you update translations (`cd builddir && make lupdate`)?

- [ ] If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker?

2022-01-27 21:29 UTC, mzanetti requested changes

2022-01-27 21:29 UTC, mzanetti commented on sma/meta.json
> +        "Energy"
needs to be lowercase "energy"

2022-02-18 12:03 UTC, mzanetti commented on sma/speedwireinverterrequest.cpp
> +* Copyright 2013 - 2021, nymea GmbH
22

2022-02-21 11:43 UTC, mzanetti approved these changes

2022-02-21 12:06 UTC, t-mon commented on sma/speedwirediscovery.cpp
> +        return;
There is a dedicated timeout for this type of discovery, in any case, if the thing discovery info timouts before this one is finished, the object does not exist any more.

2022-02-21 12:07 UTC, t-mon commented on sma/integrationpluginsma.cpp
> +    m_refreshTimer = hardwareManager()->pluginTimerManager()->registerTimer(2);
Agreed, but it keeps the timers in the resource as clean as possible.

Also, the refresh method itself returns immediatly if there is a refresh cycle still in progress, so I think we are good regarding overloading.

2022-03-29 10:28 UTC, merged