Shelly: Add support for Shelly EM
nymea/nymea-plugins pull request #538
Opened 2022-02-06 21:49 UTC by loosrob

nymea-plugins pull request checklist:

- [x] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [x] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [x] Did you update the plugin's README.md accordingly?

- [x] Did you update translations (`cd builddir && make lupdate`)?

- [x] If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker?

2022-02-06 22:54 UTC, mzanetti requested changes
Nice!
I started to review but there seem to be a lot of unwanted changes. For example the removal of shellyI3 settings, support for the shelly vintage... I have the feeling that you started with an outdated branch and need to rebase your changes onto the latest master?

2022-02-06 22:54 UTC, mzanetti commented on shelly/integrationpluginshelly.cpp
> +#include "math.h"
there's also qmath.h. API and results would be the same (except qsqrt() instead of sqrt()) but it would be more portable to different compilers/operating systems.

2022-02-06 22:54 UTC, mzanetti commented on shelly/integrationpluginshelly.cpp
> +    {shellyEmPowerActionTypeId, shellyEmThingClassId}, // move power to switch child?
No, if it's just a single output on the shelly device, having it on the gateway is the proper thing to do. the comment can go away.

2022-02-06 22:54 UTC, mzanetti commented on shelly/integrationpluginshelly.cpp
> +    {shellyEmPowerActionTypeId, shellyEmPowerActionPowerParamTypeId}, // move power to switch child?
same. code is correct, comment can be removed.

2022-02-06 22:54 UTC, mzanetti commented on shelly/integrationpluginshelly.cpp
> +            namePattern = QRegExp("^shellydimmer(2)?-[0-9A-Z]+$");
hmm... something's wrong here... This change is not supposed to be in here...
Looks like you've based off from a stale branch?

2022-02-07 18:54 UTC, loosrob commented
Hi, thanks for the comments. I based myself on the master branch (I think) but that seems to be 7 months old, so perhaps I did something wrong there?

<img width="366" alt="Schermafbeelding 2022-02-07 om 19 52 48" src="https://user-images.githubusercontent.com/79396812/152852808-c1d3690a-21b0-47b6-8b5e-aa61b9c36270.png">

I processed your other changes (qmath, removal of comments w.r.t. switchChild), but could use some help to rebase it on the right branch.

2022-02-07 20:37 UTC, loosrob commented
I think I now rebased it correctly

2022-02-07 21:04 UTC, mzanetti requested changes

2022-02-07 21:08 UTC, mzanetti commented on shelly/integrationpluginshelly.json
> +                    "interfaces": ["energymeter"],
oh, and "power" maybe too? for the output switch?

2022-02-08 20:22 UTC, loosrob commented on shelly/integrationpluginshelly.json
> +                            "defaultValue": 100,
I aligned the default to the other classes in the json (also 100)

2022-02-08 20:48 UTC, loosrob commented
I think I processed all comments (except the one about signal strength, but happy to if still needed)

2022-02-08 22:25 UTC, mzanetti commented on shelly/integrationpluginshelly.json
> +                            "defaultValue": 100,
Yes, I know. I've recently changed that for the others in this PR: https://github.com/nymea/nymea-plugins/pull/537

2022-02-09 08:02 UTC, loosrob commented on shelly/integrationpluginshelly.json
> +                            "defaultValue": 100,
OK, will update :)

2022-03-02 11:29 UTC, mzanetti approved these changes

2022-03-29 10:28 UTC, merged