Keba: Add series capability check and fetch product information during setup
nymea/nymea-plugins pull request #543
Opened 2022-02-17 16:35 UTC by t-mon

nymea-plugins pull request checklist:

- [x] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [x] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [x] Did you update the plugin's README.md accordingly?

- [x] Did you update translations (`cd builddir && make lupdate`)?

- [x] If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker?

2022-02-17 18:42 UTC, mzanetti requested changes

2022-02-17 18:42 UTC, mzanetti commented on keba/kebaproductinfo.h
> +        ConnectorCabel
Typo, Cable, but I guess "Wire" would be the most common term in our this context

2022-02-17 18:42 UTC, mzanetti commented on keba/kebaproductinfo.h
> +    enum Cabel {
Wire, or Cable

2022-02-17 18:42 UTC, mzanetti commented on keba/integrationpluginkeba.cpp
> +            if (productInformation.isValid()) {
I wonder if we shouldn't bail out instead of pass when the product string can't be parsed... Do you think there is any situation where the product string cannot be processed but all the rest would still work?

2022-02-18 05:21 UTC, t-mon commented on keba/kebaproductinfo.h
> +        ConnectorCabel
_A wire is a single conductor(material most commonly being copper or aluminium) while cable is two or more insulated wires wrapped in one jacket._

I think cable is more accuarte...

2022-03-29 15:36 UTC, closed without merging