Fronius: Rework plugin entierly, queue request and simplify structure for new API versions
nymea/nymea-plugins pull request #544
Opened 2022-02-21 21:14 UTC by t-mon

nymea-plugins pull request checklist:

- [ ] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [ ] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [ ] Did you update the plugin's README.md accordingly?

- [ ] Did you update translations (`cd builddir && make lupdate`)?

- [ ] If you added a new plugin, should it be added to nymea-plugins-all or nymea-plugins-maker?

2022-03-07 13:06 UTC, mzanetti requested changes

2022-03-07 13:06 UTC, mzanetti commented on fronius/integrationpluginfronius.json
> +                            "cached": false
I'd cache this as it changes "slowly" and will most likely still be the same after a nymea restart, so no point in flipping to idle and back to charging

2022-03-07 13:06 UTC, mzanetti commented on fronius/integrationpluginfronius.json
> +                            "cached": false
also this I'd cache as capacity will virtually be the same value forever (perhaps change every other month as the battery ages and capacity drops)

2022-03-07 13:06 UTC, mzanetti commented on fronius/integrationpluginfronius.json
> +                            "cached": false
also this I'd cache, because while it probably could change reasonably often during a nymea restart (update) it doesn't seem to make sense to go 55 -> 54 -> 0 -> 50, but instead 55 -> 54 -> 50 would be nicer.

2022-03-07 13:06 UTC, mzanetti commented on fronius/integrationpluginfronius.json
> +                            "cached": false
and this one I'm not sure... probably yes, because assuming we restart while critical is true, the restart would cause it go to false and then back to true, re-triggering any logic that would happen when it enters the critical state...

2022-03-07 13:49 UTC, t-mon commented on fronius/integrationpluginfronius.cpp
> +        connection->deleteLater();
The child things of the connection are pure "Thing" objects I work with, nothing to handle here. 
They get deleted by the thing manager.

2022-03-07 16:02 UTC, mzanetti commented on fronius/integrationpluginfronius.cpp
> +        connection->deleteLater();
Sorry, gotta ask again... Not sure what you mean with "pure thing objects". I do however see multiple `autoThingAppeared()` calls in the code with descriptors having the connection set as parent. There is no `autoThingDisappeared()` throughout the code though, which to me, so far, means removing the connection will leave broken and unremovable childs around, no?

2022-03-07 21:03 UTC, mzanetti commented on fronius/integrationpluginfronius.cpp
> +            m_froniusConnections.insert(connection, thing);
It's okay now, but I was thinking (without having it tried):
What if the reconfigure fails? Would it make more sense to first try creating the new one, and only if that succeeds replace the old one? With the current code, if the reconfigure fails, will it leave a thing without connection behind?

2022-03-07 21:04 UTC, mzanetti approved these changes

2022-03-09 07:14 UTC, t-mon commented on fronius/integrationpluginfronius.cpp
> +        connection->deleteLater();
`autoThingDisappeared` would only be required if the parent thing remains in the system, but one of the childs would removed from the parant thing (which is not a usecase for this device type). 

If you remove the parent, all child devices will be removed from the system. Since I only use the `thing` object and do not keep any resources for the childs in the plugin, there is nothing to clean up.

2022-03-29 10:28 UTC, merged