SMA: Improve Sunny WebBox discovery
nymea/nymea-plugins pull request #586
Opened 2022-07-20 13:34 UTC by t-mon

nymea-plugins pull request checklist:

- [x] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [x] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [x] Did you update the plugin's README.md accordingly?

- [x] Did you update translations (`cd builddir && make lupdate`)?

2022-08-04 15:30 UTC, mzanetti requested changes

2022-08-04 15:30 UTC, mzanetti commented on sma/sunnywebboxdiscovery.cpp
> +            if (m_verifiedNetworkDeviceInfos.contains(networkDeviceInfo))
You seem to never insert something into m_verifiedNetworkDeviceInfos, which, if I'm reading it correctly will cause all the initially checked devices to be checked twice.

But be aware, if you just add `m_verifiedNetworkDeviceInfos.append(networkDeviceInfo)` in `checkNetworkDevice()` after the successful verification, it will still be racy as chances are, it's pending the network reply still... But I think inserting into m_verifiedNetworkDeviceInfos right at the top of checkNetworkDevice() could work...

2022-08-04 15:30 UTC, mzanetti commented on sma/sunnywebboxdiscovery.cpp
> +    qCInfo(dcSma()) << "Discovery: SunnyWebBox: Start discovering the network...";
Network discovery starting...

Otherwise the user may start running around in his home :-P

2022-08-04 15:30 UTC, mzanetti commented on sma/sunnywebboxdiscovery.cpp
> +        reply->abort();
Hmm... I think this abort() call here would still cause the above lambda to trigger, whcih contains does the m_pendingReplies.removeAll(reply) again and then prints the HTTP error. Probably not an actual issue, but perhaps take a minute to check if the cleanup is really happening properly and its what you want.

2022-08-05 14:00 UTC, t-mon commented on sma/sunnywebboxdiscovery.cpp
> +            if (m_verifiedNetworkDeviceInfos.contains(networkDeviceInfo))
right...that's how it is ment to be used, just forgott due to lack of testing possibilities...good catch!

2022-08-09 13:57 UTC, mzanetti approved these changes

2022-08-29 22:16 UTC, merged