Go-ECharger: Add hardware V3 support (introduce API V2 HTTP and MQTT), improve discovery
nymea/nymea-plugins pull request #587
Opened 2022-07-21 08:10 UTC by t-mon

nymea-plugins pull request checklist:

- [ ] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [ ] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [ ] Did you update the plugin's README.md accordingly?

- [ ] Did you update translations (`cd builddir && make lupdate`)?

2022-08-04 16:14 UTC, mzanetti requested changes

2022-08-04 16:14 UTC, mzanetti commented on goecharger/integrationplugingoecharger.cpp
> +            connect(info, &ThingActionInfo::aborted, reply, &QNetworkReply::abort);
For the warning "calling finish on an already finished object", I'd be open to patch ThingXyzInfo classes to verify if the plugin developer finished() himself inside the aborted() signal and make this an actual feature... I could imagine it may actually be useful to provide a custom ErrorCode and displayMessage in the aborted() signal.

2022-08-04 16:37 UTC, mzanetti commented on goecharger/integrationplugingoecharger.cpp
> +            connect(info, &ThingActionInfo::aborted, reply, &QNetworkReply::abort);
Here's a propsal: https://github.com/nymea/nymea/pull/552

That said, if we agree to do this change in nymea:core, I'm still not sure if HardwareNotAvailable is what you want... Perhaps you'd want to keep the timeout error instead?

2022-08-10 10:12 UTC, t-mon commented on goecharger/integrationplugingoecharger.cpp
> +            connect(info, &ThingActionInfo::aborted, reply, &QNetworkReply::abort);
Well, if http did not work, from the acion perspecive...the hardware does not seem to be available for performing the action. If that's a timout error or a not reachable error is not making a difference for the action. So no changes here ok?

2022-08-10 10:30 UTC, mzanetti approved these changes

2022-08-29 22:16 UTC, merged