Shelly flood smoke gas
nymea/nymea-plugins pull request #614
Opened 2022-10-13 10:04 UTC by mzanetti

nymea-plugins pull request checklist:

- [ ] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [ ] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [ ] Did you update the plugin's README.md accordingly?

- [ ] Did you update translations (`cd builddir && make lupdate`)?

2022-10-13 11:26 UTC, t-mon requested changes

2022-10-13 11:26 UTC, t-mon commented on shelly/integrationpluginshelly.cpp
> +        connect(reply, &QNetworkReply::finished, &QNetworkReply::deleteLater);
isn't clang complaining about this?

        connect(reply, &QNetworkReply::finished, reply, &QNetworkReply::deleteLater);

2022-10-13 11:26 UTC, t-mon commented on shelly/integrationpluginshelly.cpp
> +        QNetworkReply *reply = hardwareManager()->networkManager()->get(QNetworkRequest(url));
Could be a method actually since you repeat this code section quiet a lot here:
```
void sendActionRequest(ActionInfo *info, const QUrl &url) {
        QNetworkReply *reply = hardwareManager()->networkManager()->get(QNetworkRequest(url));
        connect(reply, &QNetworkReply::finished, &QNetworkReply::deleteLater);
        connect(reply, &QNetworkReply::finished, info, [info, reply](){
            info->finish(reply->error() == QNetworkReply::NoError ? Thing::ThingErrorNoError : Thing::ThingErrorHardwareFailure);
        });
}
```

2022-10-13 13:23 UTC, mzanetti commented on shelly/integrationpluginshelly.cpp
> +        connect(reply, &QNetworkReply::finished, &QNetworkReply::deleteLater);
uh oh... Good catch! clang doesn't seem to complain for me, however, it seems that this plugin was leaking all the action network replies. Fixed now.

2022-10-13 13:30 UTC, mzanetti commented on shelly/integrationpluginshelly.cpp
> +        QNetworkReply *reply = hardwareManager()->networkManager()->get(QNetworkRequest(url));
I just tried as it seemed sensible, but there are too many subtle differences to come up with something generic enough easily.

2022-10-18 11:01 UTC, t-mon approved these changes

2022-10-28 08:14 UTC, closed without merging