add note regarding time sync needed to display total power consumption
nymea/nymea-plugins pull request #627
Opened 2022-11-16 21:31 UTC by Danfro

The shelly plug allows to display the total power consumed since it was last plugged in.
For the plug to set the timestamp for the meter, it needs to sync the time once with an internet time server.
Without the timestamp set=the time synced, no total consumption is shown.

This PR adds a note for the user to explain this behaviour.

2022-11-17 09:11 UTC, mzanetti requested changes

2022-11-17 15:35 UTC, Danfro commented on shelly/README.md
> +### Note for the Shelly Plug/PlugS
That does make sense. I rephrased accordingly.

2022-11-17 16:40 UTC, Danfro commented on shelly/README.md
> +To display the total consumed power by a meter device, it needs to sync the time once with an internet time server so it can set the timestamp for comparing. Without that, the total is always returne
I like your simple version. :+1: 

How about "Shelly devices require an internet connection to sync the time for the total energy counters to work. The timeserver can be configured in the devices webinterface."

I think to remember that the default time server is `shelly.cloud`. But since I changed that, I can't check.

2022-11-17 16:45 UTC, mzanetti commented on shelly/README.md
> +To display the total consumed power by a meter device, it needs to sync the time once with an internet time server so it can set the timestamp for comparing. Without that, the total is always returne
Yes, your final proposal is perfect.

I just checked 2 of my shellies, and both have time.google.com set. I have never changed this on any of mine. Anyhow, as your final proposal doesn't mention it any more, it doesn't really matter any more anyways.

2022-11-17 19:48 UTC, Danfro commented on shelly/README.md
> +To display the total consumed power by a meter device, it needs to sync the time once with an internet time server so it can set the timestamp for comparing. Without that, the total is always returne
Great, thanks for your thoughts. I pushed that version right now.

2022-11-18 13:29 UTC, mzanetti approved these changes

2022-12-21 13:11 UTC, merged