Keba: Add support for P30 PV Edition
nymea/nymea-plugins pull request #741
Opened 2024-07-26 09:36 UTC by t-mon

nymea-plugins pull request checklist:

- [ ] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [ ] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [ ] Did you update the plugin's README.md accordingly?

- [ ] Did you update translations (`cd builddir && make lupdate`)?

2024-07-31 09:42 UTC, martinlukas84 requested changes

2024-07-31 09:42 UTC, martinlukas84 commented on keba/kebaproductinfo.h
Shouldn't the copyright be also until 2024 as changed in .cpp file?

2024-07-31 09:42 UTC, martinlukas84 commented on keba/kebaproductinfo.cpp
> +     // KC-P30-EC24012 2 -E0R
Be consequent with empty line after type comment ;-)

2024-08-07 09:16 UTC, t-mon commented on keba/kebaproductinfo.h
Updated all file which have changed

2024-08-07 09:23 UTC, martinlukas84 approved these changes

2024-08-07 09:34 UTC, martinlukas84 approved these changes

2024-10-03 13:54 UTC, merged